<?php
session_start();
$username=$_POST['username'];
$password=$_POST['password'];
$con=mysqli_connect('localhost','root','root');
mysqli_select_db($con,'project');
$q="select *from login_details where username='$username' and password='$password';";
$result=mysqli_query($con,$q);
$num=mysqli_num_rows($result);
if($num==1)
{
	$_SESSION['username']=$username;
	header('location:http://localhost/Project/home.php');
}
else
{
	header('location:http://localhost/Project/Login.php');
}
mysqli_close($con);
?>